FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

# Installer PostgreSQL + SSH
RUN apt-get update \
    && apt-get install -y --no-install-recommends postgresql postgresql-contrib openssh-server sudo python3 python3-pip \
    && mkdir -p /run/sshd \
    && echo 'root:ansible' | chpasswd \
    && sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

EXPOSE 22 5432

COPY db1-entrypoint.sh /db1-entrypoint.sh
# Fins de ligne Unix (éviter "no such file or directory" si CRLF)
RUN sed -i 's/\r$//' /db1-entrypoint.sh && chmod +x /db1-entrypoint.sh

# Lancer via bash explicitement (évite problème shebang)
CMD ["/bin/bash", "/db1-entrypoint.sh"]
